using Application.Activities.DTOs;
using FluentValidation;

namespace Application.Activities.Validators;

// We derive from the AbstractValidator and giving it a type of the CreateActivity.Command which means that the validator will look at the properties defined in the command (in this case it is the ActivityDto which is of type CreateActivityDto) so we can set rules for all of the CreateActivityDto fields in the constructor.
// Note that we need to add this as a service in thr Program.cs file.
// The CreateActivityValidator class is responsible for validating the incoming data when creating a new activity. It inherits from the BaseActivityValidator class, which is a generic class that defines the common validation rules for both creating and editing activities. The CreateActivityValidator constructor calls the base constructor and passes in a selector function that specifies how to access the ActivityDto properties from the CreateActivity.Command object. This allows us to reuse the validation rules defined in the BaseActivityValidator for both creating and editing activities without having to duplicate the validation logic in separate validator classes. By using this approach, we can ensure that the same validation rules are consistently applied to both operations, and we can easily maintain and update the validation logic in one place (the BaseActivityValidator) without having to make changes in multiple validator classes.
// This is a base validator class that can be used for both creating and editing activities. It takes in a selector function that allows us to specify which DTO we want to validate (either CreateActivityDto or EditActivityDto). The constructor of the base validator defines the common validation rules for all the properties of the activity, such as Title, Description, Date, Category, City, Venue, Latitude, and Longitude. By using this base validator, we can avoid duplicating the same validation rules in both the CreateActivityValidator and EditActivityValidator classes, and instead just inherit from this base class and provide the appropriate selector function for the specific DTO we want to validate.
// Note that we need to add this as a service in the Program.cs file.
// The BaseActivityValidator class is a generic class that inherits from AbstractValidator<T>, where T is the type of the command that we want to validate (either CreateActivity.Command or EditActivity.Command). The TDto type parameter is constrained to be a subclass of BaseActivityDto, which means that it can only be used with DTOs that inherit from BaseActivityDto. The constructor of the BaseActivityValidator takes in a selector function that allows us to specify how to access the DTO properties from the command object. This way, we can define the validation rules for the common properties of the activity in one place, and then reuse this base validator for both creating and editing activities by providing the appropriate selector function for each case.
public class BaseActivityValidator<T, TDto> : AbstractValidator<T> where TDto : BaseActivityDto
{
    // The constructor of the BaseActivityValidator class defines the validation rules for the common properties of the activity. It uses the RuleFor method to specify the validation rules for each property, such as Title, Description, Date, Category, City, Venue, Latitude, and Longitude. The selector function is used to access the properties of the DTO from the command object, allowing us to apply the same validation rules regardless of whether we are validating a CreateActivity.Command or an EditActivity.Command. For example, we can use the selector function to access the Title property of the DTO and apply the NotEmpty and MaximumLength validation rules to ensure that the title is not empty and does not exceed 100 characters. By defining these validation rules in the base validator, we can ensure that they are consistently applied to both creating and editing activities without having to duplicate the validation logic in separate validator classes. Here, the selector function is a lambda expression that takes in the command object (of type T) and returns the corresponding DTO (of type TDto) that we want to validate. This allows us to access the properties of the DTO and apply the validation rules to them using the RuleFor method.
    public BaseActivityValidator(Func<T, TDto> selector)
    {
        RuleFor(x => selector(x).Title).NotEmpty().WithMessage("Title is required").MaximumLength(100).WithMessage("Title must not exceed 100 characters");
        RuleFor(x => selector(x).Description).NotEmpty().WithMessage("Description is required");
        RuleFor(x => selector(x).Date).GreaterThan(DateTime.UtcNow).WithMessage("Date must be in the future");
        RuleFor(x => selector(x).Category).NotEmpty().WithMessage("Category is required");
        RuleFor(x => selector(x).City).NotEmpty().WithMessage("City is required");
        RuleFor(x => selector(x).Venue).NotEmpty().WithMessage("Venue is required");
        RuleFor(x => selector(x).Latitude).NotEmpty().WithMessage("Latitude is required").InclusiveBetween(-90, 90).WithMessage("Latitude must be between -90 and 90");
        RuleFor(x => selector(x).Longitude).NotEmpty().WithMessage("Longitude is required").InclusiveBetween(-180, 180).WithMessage("Longitude must be between -180 and 180");
    }
}
